(()=>{
const blockMultiTouch=e=>{if((e.touches&&e.touches.length>=2)||(e.scale&&e.scale!==1))e.preventDefault()};
['gesturestart','gesturechange','gestureend'].forEach(type=>document.addEventListener(type,e=>e.preventDefault(),{passive:false}));
document.addEventListener('touchstart',blockMultiTouch,{passive:false});
document.addEventListener('touchmove',blockMultiTouch,{passive:false});
function fitViewport(){const h=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--app-height',`${Math.round(h)}px`)}
fitViewport();addEventListener('resize',fitViewport,{passive:true});addEventListener('orientationchange',()=>setTimeout(fitViewport,120),{passive:true});
if(window.visualViewport){window.visualViewport.addEventListener('resize',fitViewport,{passive:true});window.visualViewport.addEventListener('scroll',fitViewport,{passive:true})}

const questionSets={
 P3:[{id:'Q1',src:'assets/P3_Q1.jpeg'},{id:'Q2',src:'assets/P3_Q2.jpeg'},{id:'Q3',src:'assets/P3_Q3.jpeg'}],
 P4:[{id:'Q1',src:'assets/P4_Q1.jpeg'},{id:'Q2',src:'assets/P4_Q2.jpeg'},{id:'Q3',src:'assets/P4_Q3.jpeg'}],
 P5:[{id:'Q1',src:'assets/P5_Q1.jpeg'},{id:'Q2',src:'assets/P5_Q2.jpeg'},{id:'Q3',src:'assets/P5_Q3.jpeg'}],
 P6:[{id:'Q1',src:'assets/P6_Q1.jpeg'},{id:'Q2',src:'assets/P6_Q2.jpeg'},{id:'Q3',src:'assets/P6_Q3.jpeg'}]
};
const scenes=[{id:'wheel'},{id:'plinko'},{id:'arena'},{id:'rail'},{id:'gate'},{id:'bowl'}];
const appRoot=document.getElementById('app'),packBtn=document.getElementById('packBtn'),soundBtn=document.getElementById('soundBtn'),drawBtn=document.getElementById('drawBtn'),sceneEl=document.getElementById('scene'),packPicker=document.getElementById('packPicker'),packOptions=[...document.querySelectorAll('.pack-option')],revealBridge=document.getElementById('revealBridge'),result=document.getElementById('result'),resultPackBtn=document.getElementById('resultPackBtn'),winner=document.getElementById('winner'),resultImg=document.getElementById('resultImg'),questionFrame=document.getElementById('questionFrame'),nextBtn=document.getElementById('nextBtn'),toast=document.getElementById('toast');
const STATE={PACK:'PACK_SELECT',READY:'READY',FOCUSING:'FOCUSING',ANIMATING:'ANIMATING',REVEALING:'REVEALING',QUESTION:'QUESTION'};
let appState=STATE.PACK,activePack=null,questions=questionSets.P3,recentQuestions=[],recentScenes=[],busy=false,audioCtx=null,drawCount=0;
let soundOn=(()=>{try{return localStorage.getItem('lucky.sound')!=='off'}catch{return true}})();
const reduceMotion=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches||false;
const V12=window.V12||null;
const Q_COLORS=['#5B9CFF','#FF6659','#53C878'],Q_TINTS=['#10233F','#361A1A','#153523'],INK='#F5F7FA',MUTED='#AAB2BD';
const STAGE_BG='#080B10',STAGE_SURFACE='#111720',STAGE_SURFACE_2='#171E28',STAGE_EDGE='#323B48',STAGE_SOFT='#202833';
const rnd=max=>{if(crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}return Math.floor(Math.random()*max)};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const phase=(p,a,b)=>clamp((p-a)/(b-a));
const smooth=t=>{t=clamp(t);return t*t*(3-2*t)};
const easeOutCubic=t=>1-Math.pow(1-clamp(t),3);
const easeInOutQuint=t=>{t=clamp(t);return t<.5?16*t*t*t*t*t:1-Math.pow(-2*t+2,5)/2};
const easeOutBack=t=>{t=clamp(t);const c1=1.35,c3=c1+1;return 1+c3*Math.pow(t-1,3)+c1*Math.pow(t-1,2)};
function setState(next){appState=next;busy=[STATE.FOCUSING,STATE.ANIMATING,STATE.REVEALING].includes(next);document.body.dataset.state=next;drawBtn.disabled=busy||!activePack;packBtn.disabled=busy}
function qIndex(q){return Math.max(0,questions.findIndex(x=>x.id===q.id))}
function qColor(q){return Q_COLORS[qIndex(q)]}
function toastMsg(m){toast.textContent=m;toast.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toast.classList.remove('show'),1100)}
function ensureAudio(){if(!soundOn)return null;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audioCtx||=new AC();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}catch{return null}}
function tone(freq=500,d=.05,type='sine',gain=.018,slide=0){const ac=ensureAudio();if(!ac)return;try{const now=ac.currentTime,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+d);g.gain.setValueAtTime(Math.max(.0001,gain),now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g).connect(ac.destination);o.start(now);o.stop(now+d+.01)}catch{}}
function noise(d=.045,gain=.012,cutoff=1800){const ac=ensureAudio();if(!ac)return;try{const len=Math.max(1,Math.floor(ac.sampleRate*d)),buf=ac.createBuffer(1,len,ac.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=ac.createBufferSource(),f=ac.createBiquadFilter(),g=ac.createGain();src.buffer=buf;f.type='bandpass';f.frequency.value=cutoff;f.Q.value=.9;g.gain.setValueAtTime(gain,ac.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+d);src.connect(f).connect(g).connect(ac.destination);src.start();src.stop(ac.currentTime+d)}catch{}}
function sfx(kind,intensity=1){if(!soundOn)return;const k=clamp(intensity,.25,1.5);if(kind==='tick'){tone(980,.025,'triangle',.009*k,-90)}else if(kind==='peg'){tone(720,.034,'sine',.012*k,-180);noise(.028,.004*k,2400)}else if(kind==='impact'){tone(180,.055,'triangle',.018*k,-45);noise(.04,.010*k,900)}else if(kind==='metal'){tone(1180,.035,'triangle',.010*k,-260);tone(510,.055,'sine',.006*k,-80)}else if(kind==='gate'){tone(260,.055,'square',.012*k,-55);noise(.035,.006*k,1300)}else if(kind==='roll'){tone(620,.018,'sine',.0045*k,-80)}else if(kind==='capture'){tone(430,.06,'triangle',.015*k,90);tone(690,.09,'sine',.010*k,120)}}
function resultTone(){[[523,.07],[659,.08],[784,.12]].forEach(([f,d],i)=>setTimeout(()=>tone(f,d,'sine',.018),i*72))}
function stepEvent(state,key,value,fn){const k='_step_'+key,prev=state[k];if(prev===undefined){state[k]=value;return}if(value!==prev){state[k]=value;if(!state.mutedEvents)fn(value,prev)}}
function onceEvent(state,key,condition,fn){const k='_once_'+key;if(condition&&!state[k]){state[k]=true;if(!state.mutedEvents)fn()}}
function soundSvg(on){return on?'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M3 9v6h4l5 4V5L7 9H3zm13.5 3c0-1.4-.8-2.6-2-3.2v6.4c1.2-.6 2-1.8 2-3.2zm-2-7v2.1c2.1.8 3.5 2.7 3.5 4.9s-1.4 4.1-3.5 4.9V19c3.2-.9 5.5-3.6 5.5-7s-2.3-6.1-5.5-7z"/></svg>':'<svg viewBox="0 0 24 24"><path fill="currentColor" d="M16.5 12c0-.7-.2-1.4-.5-2l1.5-1.5c.7 1 1 2.2 1 3.5 0 1.1-.2 2.1-.7 3l-1.6-1.6c.2-.4.3-.9.3-1.4zM3 9v6h4l5 4v-4.2L6.2 9H3zm9-4-3.1 2.5L12 10.6V5zm8.3 15.7L3.3 3.7 4.7 2.3l17 17-1.4 1.4z"/></svg>'}
function updateSound(){soundBtn.innerHTML=soundSvg(soundOn);soundBtn.setAttribute('aria-label',soundOn?'關閉音效':'開啟音效')}
Object.values(questionSets).flat().forEach(q=>{const im=new Image();im.src=q.src});

let keyboardNavigation=false;
document.addEventListener('keydown',e=>{if(['Tab','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))keyboardNavigation=true},{capture:true});
document.addEventListener('pointerdown',()=>{keyboardNavigation=false},{capture:true,passive:true});
function showPackPicker(){if(busy)return;packOptions.forEach(b=>b.classList.toggle('is-selected',b.dataset.pack===activePack));packPicker.classList.add('show');packPicker.setAttribute('aria-hidden','false');appRoot.inert=true;result.inert=true;setState(STATE.PACK);if(keyboardNavigation)setTimeout(()=>((packOptions.find(b=>b.dataset.pack===activePack)||packOptions[0])?.focus({preventScroll:true})),0)}
function hidePackPicker(){packPicker.classList.remove('show');packPicker.setAttribute('aria-hidden','true');appRoot.inert=false;result.inert=false;if(activePack)setState(STATE.READY)}
function selectPack(pack){if(!questionSets[pack]||busy)return;activePack=pack;questions=questionSets[pack];recentQuestions=[];recentScenes=[];drawCount=0;packBtn.textContent=pack;resultPackBtn.textContent=pack;hidePackPicker();setState(STATE.READY)}
function packFromUrl(){const parts=location.pathname.split('/').filter(Boolean),last=(parts.at(-1)||'').toUpperCase();if(questionSets[last])return last;const params=new URLSearchParams(location.search),q=(params.get('pack')||params.get('p')||'').toUpperCase();if(questionSets[q])return q;const h=location.hash.replace(/^#/,'').toUpperCase();return questionSets[h]?h:null}
function chooseQuestion(){const blocked=new Set(recentQuestions.slice(0,2));const pool=[0,1,2].filter(i=>!blocked.has(i));const pick=pool[rnd(pool.length)];recentQuestions=[pick,...recentQuestions].slice(0,2);return pick}
function chooseScene(){const blocked=new Set(recentScenes.slice(0,3));const pool=scenes.filter(s=>!blocked.has(s.id));const pick=pool[rnd(pool.length)];recentScenes=[pick.id,...recentScenes].slice(0,3);return pick}

/* ---------- SVG motion system ---------- */
const NS='http://www.w3.org/2000/svg';
function S(tag,attrs={},parent){const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))if(v!==undefined&&v!==null)el.setAttribute(k,String(v));if(parent)parent.appendChild(el);return el}
function SA(el,attrs){for(const [k,v] of Object.entries(attrs))if(v!==undefined&&v!==null)el.setAttribute(k,String(v));return el}
function T(el,x=0,y=0,rot=0,sx=1,sy=sx){el.setAttribute('transform',`translate(${x} ${y}) rotate(${rot}) scale(${sx} ${sy})`)}
function txt(parent,text,x,y,size=28,attrs={}){const e=S('text',{x,y,'text-anchor':'middle','dominant-baseline':'middle','font-size':size,'font-weight':attrs.weight||650,fill:attrs.fill||INK,'font-family':'Roboto, Arial, PingFang TC, sans-serif',...attrs},parent);e.textContent=text;return e}
function sector(cx,cy,r,a0,a1){const rad=d=>d*Math.PI/180,x0=cx+r*Math.cos(rad(a0)),y0=cy+r*Math.sin(rad(a0)),x1=cx+r*Math.cos(rad(a1)),y1=cy+r*Math.sin(rad(a1));return `M ${cx} ${cy} L ${x0} ${y0} A ${r} ${r} 0 0 1 ${x1} ${y1} Z`}
function seed01(n,s=0){const x=Math.sin(n*12.9898+s*78.233)*43758.5453;return x-Math.floor(x)}
function addDefs(svg){
 const d=S('defs',{},svg);
 const sh=S('filter',{id:'shadow',x:'-40%',y:'-40%',width:'180%',height:'200%'},d);S('feDropShadow',{dx:0,dy:14,stdDeviation:18,'flood-color':'#000000','flood-opacity':.42},sh);
 const soft=S('filter',{id:'softShadow',x:'-50%',y:'-50%',width:'200%',height:'220%'},d);S('feDropShadow',{dx:0,dy:9,stdDeviation:12,'flood-color':'#000000','flood-opacity':.34},soft);
 const glass=S('linearGradient',{id:'glass',x1:0,y1:0,x2:0,y2:1},d);S('stop',{offset:0,'stop-color':'#1C2531','stop-opacity':.98},glass);S('stop',{offset:.56,'stop-color':'#121922','stop-opacity':.94},glass);S('stop',{offset:1,'stop-color':'#0B1017','stop-opacity':.98},glass);
 const metal=S('linearGradient',{id:'metal',x1:0,y1:0,x2:0,y2:1},d);S('stop',{offset:0,'stop-color':'#596675'},metal);S('stop',{offset:.52,'stop-color':'#2D3743'},metal);S('stop',{offset:1,'stop-color':'#151B23'},metal);
 const ceramic=S('radialGradient',{id:'ceramic',cx:.32,cy:.25,r:.78},d);S('stop',{offset:0,'stop-color':'#ffffff'},ceramic);S('stop',{offset:.46,'stop-color':'#f5f7fa'},ceramic);S('stop',{offset:1,'stop-color':'#cfd5dc'},ceramic);
 const pearl=S('radialGradient',{id:'pearl',cx:.30,cy:.24,r:.82},d);S('stop',{offset:0,'stop-color':'#ffffff'},pearl);S('stop',{offset:.38,'stop-color':'#f8fafc'},pearl);S('stop',{offset:.72,'stop-color':'#e5e9ee'},pearl);S('stop',{offset:1,'stop-color':'#bcc3cb'},pearl);
 const graphite=S('linearGradient',{id:'graphite',x1:0,y1:0,x2:0,y2:1},d);S('stop',{offset:0,'stop-color':'#AEB8C4'},graphite);S('stop',{offset:.48,'stop-color':'#667281'},graphite);S('stop',{offset:1,'stop-color':'#323B46'},graphite);
 const titanium=S('linearGradient',{id:'titanium',x1:0,y1:0,x2:0,y2:1},d);S('stop',{offset:0,'stop-color':'#ffffff'},titanium);S('stop',{offset:.50,'stop-color':'#e7ebef'},titanium);S('stop',{offset:1,'stop-color':'#aeb6bf'},titanium);
 const wood=S('linearGradient',{id:'wood',x1:0,y1:0,x2:1,y2:0},d);S('stop',{offset:0,'stop-color':'#bd8745'},wood);S('stop',{offset:.42,'stop-color':'#edc783'},wood);S('stop',{offset:.72,'stop-color':'#d6a65e'},wood);S('stop',{offset:1,'stop-color':'#ad7839'},wood);
}
function addBackdrop(svg){
 const d=S('defs',{},svg);const rg=S('radialGradient',{id:'stageGlow',cx:.5,cy:.42,r:.68},d);S('stop',{offset:0,'stop-color':'#17202B'},rg);S('stop',{offset:.54,'stop-color':'#0D1219'},rg);S('stop',{offset:1,'stop-color':'#06080C'},rg);
 S('rect',{x:0,y:0,width:1000,height:700,fill:'url(#stageGlow)'},svg);S('ellipse',{cx:500,cy:612,rx:310,ry:34,fill:'#000',opacity:.34},svg)
}
function addHalo(parent,x,y,r=76,color='#7E8996'){const g=S('g',{opacity:0},parent);S('circle',{cx:x,cy:y,r:r*1.35,fill:'#081019',opacity:.78},g);S('circle',{cx:x,cy:y,r,fill:'none',stroke:color,'stroke-width':6,'stroke-opacity':.95},g);return g}

/* v11.1 motion language: short after-images, impact registration and a restrained camera settle.
   Inspired by frame-by-frame motion-graphics practice, but kept flash-free for classroom use. */
function addTrail(parent,r=18,count=3){const g=S('g',{'pointer-events':'none'},parent),dots=[];for(let i=0;i<count;i++)dots.push(S('circle',{cx:0,cy:0,r:r*(1-i*.10),fill:'#c9cfd6',stroke:'#fff','stroke-width':1.4,opacity:0},g));return{g,dots}}
function updateTrail(tr,state,key,x,y,t,activity=1,color='#c9cfd6'){if(!tr)return;if(reduceMotion){tr.dots.forEach(e=>SA(e,{opacity:0}));return}const hk='_trail_'+key,h=state[hk]||(state[hk]=[]),last=h[h.length-1];if(!last||t-last.t>.012)h.push({t,x,y});while(h.length&&t-h[0].t>.24)h.shift();const speed=last?Math.hypot(x-last.x,y-last.y)/Math.max(.001,t-last.t):0,strength=clamp((speed-70)/760)*clamp(activity);const lags=[.034,.070,.112];tr.dots.forEach((el,i)=>{const tt=t-lags[i];let pt=h[0]||{x,y};for(let j=h.length-1;j>=0;j--){if(h[j].t<=tt){pt=h[j];break}}T(el,pt.x,pt.y,0,1-i*.08);SA(el,{fill:color,opacity:strength*(.26-i*.055)})})}
function addImpactRing(parent,r=18){return S('circle',{cx:0,cy:0,r,fill:'none',stroke:'#b9c0c8','stroke-width':3,opacity:0,'pointer-events':'none'},parent)}
function impactRing(el,x,y,u,color='#b9c0c8',power=1){if(!el)return;u=clamp(u);const k=(1-smooth(phase(u,0,.42)))*power;SA(el,{cx:x,cy:y,r:18+u*31,stroke:color,'stroke-width':lerp(3,1.2,u),opacity:reduceMotion?0:k*.42})}
function cameraSettle(svg,p,seed,extra){if(!svg)return;const nodes=[svg,extra].filter(Boolean);if(reduceMotion){nodes.forEach(n=>n.style.transform='translateZ(0)');return}const u=phase(p,.895,.995),pulse=Math.sin(u*Math.PI)*(1-u*.42),sign=seed01(97,seed)>.5?1:-1,tr=`translate3d(${(sign*pulse*1.8).toFixed(2)}px,${(-pulse*2.2).toFixed(2)}px,0) scale(${(1+pulse*.008).toFixed(4)})`;nodes.forEach(n=>{n.style.transformOrigin='50% 50%';n.style.transform=tr})}

/* Wheel — the selector is visible, the three candidates are always visible. */
function buildWheel(svg,state){
 const root=S('g',{},svg),frame=S('g',{filter:'url(#shadow)'},root);S('circle',{cx:500,cy:352,r:244,fill:STAGE_SURFACE,stroke:'#3A4654','stroke-width':18},frame);S('circle',{cx:500,cy:352,r:218,fill:STAGE_SURFACE_2},frame);
 state.sectors=[];state.labels=[];state.wheel=S('g',{},root);
 for(let i=0;i<3;i++){const a0=-90+i*120,a1=a0+120,seg=S('path',{d:sector(500,352,204,a0,a1),fill:Q_COLORS[i],stroke:'#fff','stroke-width':6},state.wheel);state.sectors.push(seg);const mid=(a0+a1)/2*Math.PI/180;const label=txt(state.wheel,`Q${i+1}`,500+Math.cos(mid)*116,352+Math.sin(mid)*116,32,{fill:'#fff',weight:720});state.labels.push(label)}
 state.speedLines=S('g',{opacity:0},root);for(let i=0;i<12;i++)S('line',{x1:500,y1:101,x2:500,y2:78,stroke:'#7f8790','stroke-width':3,'stroke-linecap':'round',opacity:.50,transform:`rotate(${i*30} 500 352)`},state.speedLines);
 S('circle',{cx:500,cy:352,r:62,fill:STAGE_SURFACE_2,stroke:'#3A4654','stroke-width':3,filter:'url(#softShadow)'},root);S('circle',{cx:500,cy:352,r:32,fill:'url(#titanium)',stroke:'#9aa0a6','stroke-width':2},root);S('circle',{cx:490,cy:342,r:8,fill:'#fff',opacity:.72},root);state.pointer=S('path',{d:'M500 76 L470 143 Q500 131 530 143 Z',fill:'url(#graphite)',stroke:'#D6DEE8','stroke-width':2,filter:'url(#softShadow)'},root);state.halo=addHalo(root,500,135,45,Q_COLORS[state.target]);state.revealPoint={x:500,y:136}
}
function updateWheel(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.02,.94):0;if(phys)phys.step(simT);const angle=phys?phys.angle*180/Math.PI:0,omega=phys?phys.omega:0,focus=smooth(phase(p,.92,1));
 if(phys)for(const ev of phys.drain()){if(state.mutedEvents)continue;if(ev.kind==='tick')sfx('tick',ev.power||.5);else if(ev.kind==='capture')sfx('capture',1)}
 state.wheel.setAttribute('transform',`rotate(${angle} 500 352)`);state.labels.forEach(el=>{const x=el.getAttribute('x'),y=el.getAttribute('y');el.setAttribute('transform',`rotate(${-angle} ${x} ${y})`)});const speed=phys?clamp(Math.abs(omega)/Math.max(.001,phys.omega0)):0,speedInk=smooth(phase(p,.035,.10))*(1-smooth(phase(p,.72,.94)))*Math.sqrt(speed);SA(state.speedLines,{opacity:reduceMotion?0:speedInk*.38,transform:`rotate(${angle*.82} 500 352)`});state.sectors.forEach((seg,i)=>SA(seg,{opacity:i===target?1:lerp(1,.40,focus)}));SA(state.halo,{opacity:focus});const pointerTap=(phys?.pointer||0)*4.2-Math.sin(focus*Math.PI)*5;SA(state.pointer,{transform:`translate(0 ${pointerTap})`,stroke:focus>.25?Q_COLORS[target]:'#D6DEE8','stroke-width':lerp(2,4,focus)})
}

/* Plinko — the three destinations stay visible; only the ball is random. */
function buildPlinko(svg,state){
 const root=S('g',{},svg);S('rect',{x:270,y:56,width:460,height:574,rx:38,fill:'url(#glass)',stroke:'#33404E','stroke-width':3,filter:'url(#shadow)'},root);S('path',{d:'M300 90 Q500 30 700 90',fill:'none',stroke:'#fff','stroke-opacity':.7,'stroke-width':10,'stroke-linecap':'round'},root);
 for(let r=0;r<8;r++){const count=7+(r%2),y=168+r*50;for(let c=0;c<count;c++){const x=350+c*(300/(count-1));S('circle',{cx:x,cy:y,r:5.5,fill:'#8994A2',stroke:'#202A35','stroke-width':1.5},root)}}
 const slots=[405,500,595];state.slotGroups=[];for(let i=0;i<3;i++){const g=S('g',{},root);S('rect',{x:slots[i]-47,y:540,width:94,height:67,rx:16,fill:Q_TINTS[i],stroke:Q_COLORS[i],'stroke-opacity':.55,'stroke-width':2},g);txt(g,`Q${i+1}`,slots[i],573,21,{fill:Q_COLORS[i],weight:760});state.slotGroups.push(g)}state.trail=addTrail(root,16,3);state.impactRing=addImpactRing(root,14);state.ball=S('g',{filter:'url(#softShadow)'},root);state.ballCore=S('circle',{cx:0,cy:0,r:19,fill:'url(#ceramic)',stroke:'#b7bec6','stroke-width':2.5},state.ball);S('circle',{cx:-6,cy:-7,r:5.5,fill:'#fff',opacity:.88},state.ball);state.halo=addHalo(root,slots[state.target],573,45,Q_COLORS[state.target]);state.revealPoint={x:slots[state.target],y:573};if(state.gl?.ok){SA(state.ball,{opacity:0});SA(state.trail.g,{opacity:0});SA(state.impactRing,{opacity:0})}
}
function updatePlinko(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.02,.925):0;if(phys)phys.step(simT);const focus=smooth(phase(p,.92,1)),x=phys?.x??500,y=phys?.y??116,vx=phys?.vx||0,vy=phys?.vy||0;
 if(phys)for(const ev of phys.drain()){if(!state.mutedEvents){if(ev.kind==='impact'){sfx('peg',ev.power||.8);state.gl?.impact(ev.x,ev.y,'#aeb5bd',ev.power||.8,ev.nx,ev.ny)}else if(ev.kind==='wall'){sfx('peg',.42);state.gl?.impact(ev.x,ev.y,'#c3c9d0',.5,ev.nx,ev.ny)}else if(ev.kind==='capture'){sfx('capture',1);state.gl?.impact(ev.x,ev.y,Q_COLORS[target],1.15,ev.nx,ev.ny)}}}
 const speed=Math.hypot(vx,vy),ang=Math.atan2(vy,vx)*180/Math.PI,stretch=(1-focus)*clamp(speed/1600)*.06,sc=lerp(1,1.16,easeOutBack(focus));T(state.ball,x,y,ang,sc*(1+stretch),sc*(1-stretch*.62));state.slotGroups.forEach((el,j)=>SA(el,{opacity:j===target?1:lerp(1,.42,focus)}));SA(state.halo,{opacity:focus});SA(state.ballCore,{stroke:focus>.12?Q_COLORS[target]:'#b7bec6','stroke-width':lerp(2.5,5,focus)});if(!state.gl?.ok)updateTrail(state.trail,state,'plinko',x,y,t,1-focus,focus>.25?Q_COLORS[target]:'#c9cfd6');if(state.gl?.ok)state.gl.ball(x,y,19*sc,{base:'#dfe4ea',edge:'#8d959e',focus:Q_COLORS[target],focusAmount:focus,vx,vy})
}

/* Physical selector helpers — candidates stay visible, the selector does the choosing. */
function candidatePuck(parent,index,r=42){
 const g=S('g',{filter:'url(#softShadow)'},parent);S('circle',{cx:0,cy:0,r,fill:STAGE_SURFACE_2,stroke:Q_COLORS[index],'stroke-width':3},g);S('circle',{cx:0,cy:0,r:r-10,fill:Q_TINTS[index]},g);txt(g,`Q${index+1}`,0,1,Math.round(r*.48),{fill:Q_COLORS[index],weight:760});S('circle',{cx:-r*.28,cy:-r*.30,r:r*.13,fill:'#fff',opacity:.78},g);return g
}
function candidatePad(parent,index,x,y,w=154,h=86){const g=S('g',{},parent);S('rect',{x:x-w/2,y:y-h/2,width:w,height:h,rx:26,fill:STAGE_SURFACE_2,stroke:'#374250','stroke-width':2,filter:'url(#softShadow)'},g);S('rect',{x:x-w/2+10,y:y-h/2+10,width:6,height:h-20,rx:3,fill:Q_COLORS[index]},g);txt(g,`Q${index+1}`,x,y+1,28,{fill:Q_COLORS[index],weight:760});return g}

/* Kinetic Arena — one neutral ceramic puck receives a single launch impulse, then ricochets through a frictionless-looking air table until one of three fixed goal pockets captures it. The outcome is encoded in a verified initial launch state; there is no mid-flight steering or object replacement. */
function buildArena(svg,state){
 const root=S('g',{},svg),table=S('g',{filter:'url(#shadow)'},root);
 S('path',{d:'M265 116 Q500 70 735 116 L828 352 Q790 582 590 625 Q500 646 410 625 Q210 582 172 352 Z',fill:STAGE_SURFACE,stroke:'#374250','stroke-width':4},table);
 S('path',{d:'M291 145 Q500 105 709 145 L792 350 Q757 548 582 588 Q500 608 418 588 Q243 548 208 350 Z',fill:STAGE_SURFACE_2,stroke:'#29333F','stroke-width':3},table);
 // Three fixed candidate goals. They are visible from the first frame and never move.
 state.goalPos=[[500,145],[292,512],[708,512]];state.goals=[];
 state.goalPos.forEach((pos,i)=>{const g=S('g',{},root);S('circle',{cx:pos[0],cy:pos[1],r:58,fill:Q_TINTS[i],stroke:Q_COLORS[i],'stroke-width':3,filter:'url(#softShadow)'},g);S('circle',{cx:pos[0],cy:pos[1],r:38,fill:STAGE_BG,opacity:.88},g);txt(g,`Q${i+1}`,pos[0],pos[1]+1,23,{fill:Q_COLORS[i],weight:760});state.goals.push(g)});
 // Neutral bumpers: the puck's course is visibly changed by these collisions.
 state.bumpers=[[385,285,42],[615,285,42],[500,415,47],[305,370,31],[695,370,31]];state.bumpers.forEach(([x,y,r])=>{const g=S('g',{filter:'url(#softShadow)'},root);S('circle',{cx:x,cy:y,r,fill:'#1A222D',stroke:'#45515F','stroke-width':4},g);S('circle',{cx:x,cy:y,r:r-11,fill:'#252F3B',stroke:'#5B6673','stroke-width':2},g);S('circle',{cx:x-r*.24,cy:y-r*.26,r:r*.13,fill:'#fff',opacity:.9},g)});
 // Spring launcher communicates the one-time initial impulse.
 state.launcher=S('g',{},root);S('rect',{x:470,y:555,width:60,height:82,rx:25,fill:'#eef2f6',stroke:'#3D4856','stroke-width':3},state.launcher);state.spring=S('path',{d:'M500 625 l-16 -12 32 -14 -32 -14 32 -14 -16 -12',fill:'none',stroke:'#9aa0a6','stroke-width':6,'stroke-linejoin':'round','stroke-linecap':'round'},state.launcher);state.plunger=S('rect',{x:480,y:530,width:40,height:28,rx:14,fill:'url(#titanium)',stroke:'#9ca3aa','stroke-width':2},state.launcher);
 state.trail=addTrail(root,20,3);state.impactRing=addImpactRing(root,20);state.puck=S('g',{filter:'url(#shadow)'},root);state.puckCore=S('circle',{cx:0,cy:0,r:23,fill:'url(#ceramic)',stroke:'#9da4ac','stroke-width':2.6},state.puck);S('ellipse',{cx:-7,cy:-8,rx:7,ry:4.5,fill:'#fff',opacity:.92},state.puck);state.puckLabel=txt(state.puck,'',0,1,16,{fill:Q_COLORS[state.target],weight:800,opacity:0});
 state.halo=addHalo(root,state.goalPos[state.target][0],state.goalPos[state.target][1],62,Q_COLORS[state.target]);
 // v12 chooses a verified launch angle before the draw; the live puck then follows only collision physics.
 state.revealPoint={x:state.goalPos[state.target][0],y:state.goalPos[state.target][1]};if(state.gl?.ok){SA(state.puck,{opacity:0});SA(state.trail.g,{opacity:0});SA(state.impactRing,{opacity:0})}
}
function updateArena(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.08,.925):0;if(phys)phys.step(simT);const focus=smooth(phase(p,.91,1));
 const compression=p<.08?smooth(phase(p,.00,.08)):1-smooth(phase(p,.08,.14));SA(state.spring,{transform:`translate(0 ${compression*16}) scale(1 ${1-compression*.18})`});SA(state.plunger,{y:530+compression*18});onceEvent(state,'arenaLaunch',p>.105,()=>sfx('metal',.78));
 if(phys)for(const ev of phys.drain()){if(!state.mutedEvents){if(ev.kind==='impact'){sfx('impact',ev.power||.8);state.gl?.impact(ev.x,ev.y,'#9fa7b0',ev.power||.9,ev.nx,ev.ny)}else if(ev.kind==='capture'){sfx('capture',1);state.gl?.impact(ev.x,ev.y,Q_COLORS[target],1.2,ev.nx,ev.ny)}}}
 const x=phys?.x??500,y=phys?.y??535,vx=phys?.vx||0,vy=phys?.vy||0,speed=Math.hypot(vx,vy),hitSquash=clamp(speed/1200)*.025,sc=lerp(1,1.12,easeOutBack(focus));T(state.puck,x,y,0,sc*(1-hitSquash),sc*(1+hitSquash));SA(state.puckCore,{stroke:focus>.12?Q_COLORS[target]:'#9da4ac','stroke-width':lerp(2.6,5,focus)});state.puckLabel.textContent=`Q${target+1}`;SA(state.puckLabel,{opacity:focus,fill:Q_COLORS[target]});state.goals.forEach((el,j)=>SA(el,{opacity:j===target?1:lerp(1,.40,focus)}));SA(state.halo,{opacity:focus});const [gx,gy]=state.goalPos[target];state.revealPoint={x:gx,y:gy};if(!state.gl?.ok)updateTrail(state.trail,state,'arena',x,y,t,1-focus,focus>.2?Q_COLORS[target]:'#c6ccd3');if(state.gl?.ok)state.gl.ball(x,y,23*sc,{base:'#dce2e8',edge:'#858e98',focus:Q_COLORS[target],focusAmount:focus,vx,vy})
}

/* Magnetic Rail — a single selector puck ricochets on a rail and is captured by one of three visible detents. */
function buildRail(svg,state){
 const root=S('g',{},svg),y=350;S('rect',{x:230,y:y-24,width:540,height:48,rx:24,fill:'#eef2f6',stroke:'#d8dde3','stroke-width':3,filter:'url(#softShadow)'},root);S('line',{x1:258,y1:y,x2:742,y2:y,stroke:'#c6ccd3','stroke-width':5,'stroke-linecap':'round'},root);S('rect',{x:218,y:y-54,width:18,height:108,rx:9,fill:'#9aa0a6'},root);S('rect',{x:764,y:y-54,width:18,height:108,rx:9,fill:'#9aa0a6'},root);
 const xs=[330,500,670];state.detents=[];state.pads=[];xs.forEach((x,i)=>{S('path',{d:`M${x-38} ${y+18} Q${x} ${y+68} ${x+38} ${y+18}`,fill:'none',stroke:'#3D4856','stroke-width':7,'stroke-linecap':'round'},root);S('circle',{cx:x,cy:y,r:40,fill:'none',stroke:Q_COLORS[i],'stroke-opacity':.10,'stroke-width':9},root);state.detents.push(S('circle',{cx:x,cy:y+7,r:29,fill:STAGE_SURFACE_2,stroke:'#465261','stroke-width':3},root));state.pads.push(candidatePad(root,i,x,515,150,82))});state.trail=addTrail(root,27,3);state.puck=S('g',{filter:'url(#shadow)'},root);S('circle',{cx:0,cy:4,r:32,fill:'#aeb4bb',opacity:.34},state.puck);state.puckCore=S('circle',{cx:0,cy:0,r:31,fill:'url(#titanium)',stroke:'#8f969e','stroke-width':2.5},state.puck);S('circle',{cx:0,cy:0,r:18,fill:'url(#ceramic)',stroke:'#d5dae0','stroke-width':1.5},state.puck);S('ellipse',{cx:-8,cy:-9,rx:7,ry:4,fill:'#fff',opacity:.80},state.puck);state.halo=addHalo(root,500,350,48,Q_COLORS[state.target]);state.revealPoint={x:500,y:350};if(state.gl?.ok){SA(state.puck,{opacity:0});SA(state.trail.g,{opacity:0})}
}
function updateRail(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.02,.94):0;if(phys)phys.step(simT);const xs=[330,500,670],focus=smooth(phase(p,.92,1)),x=phys?.x??500,y=phys?.y??350,vx=phys?.vx||0,magnet=phys?clamp((phys.time-1.65)/.45):0;
 if(phys)for(const ev of phys.drain()){if(!state.mutedEvents){if(ev.kind==='wall'){sfx('metal',ev.power||.75);state.gl?.impact(ev.x,ev.y,'#aeb6bf',.7,ev.nx,ev.ny)}else if(ev.kind==='capture'){sfx('capture',1);state.gl?.impact(ev.x,ev.y,Q_COLORS[target],1,ev.nx,ev.ny)}}}
 const squash=clamp(Math.abs(vx)/1200)*.035;T(state.puck,x,y,0,lerp(1,1.08,focus)*(1-squash),lerp(1,1.08,focus)*(1+squash));state.detents.forEach((el,i)=>SA(el,{stroke:i===target&&magnet>.15?Q_COLORS[target]:'#d7dce2','stroke-width':i===target&&magnet>.15?lerp(3,5,magnet):3}));SA(state.puckCore,{stroke:focus>.15?Q_COLORS[target]:'#8f969e','stroke-width':lerp(2.5,5,focus)});state.pads.forEach((el,i)=>SA(el,{opacity:i===target?1:lerp(1,.38,focus)}));state.halo.setAttribute('transform',`translate(${xs[target]-500} 7)`);SA(state.halo,{opacity:focus});state.revealPoint={x:xs[target],y:357};if(!state.gl?.ok)updateTrail(state.trail,state,'rail',x,y,t,1-focus,focus>.2?Q_COLORS[target]:'#c3c9d0');if(state.gl?.ok){state.gl.magneticField(xs[target],357,Q_COLORS[target],magnet*(1-focus*.35));state.gl.ball(x,y,31*lerp(1,1.08,focus),{base:'#cbd2d9',edge:'#747b83',focus:Q_COLORS[target],focusAmount:focus,vx,vy:0,metal:true})}
}

/* Timing Gate — candidates circulate continuously; an independent trigger rotor fires the fixed gate when its marker reaches the sensor. */
function buildGate(svg,state){
 const root=S('g',{},svg);S('ellipse',{cx:500,cy:342,rx:285,ry:170,fill:'none',stroke:'#26303C','stroke-width':28},root);S('ellipse',{cx:500,cy:342,rx:285,ry:170,fill:'none',stroke:'#495667','stroke-width':20},root);state.cands=[candidatePuck(root,0,40),candidatePuck(root,1,40),candidatePuck(root,2,40)];
 state.timer=S('g',{filter:'url(#softShadow)'},root);S('circle',{cx:500,cy:342,r:76,fill:STAGE_SURFACE,stroke:'#374250','stroke-width':3},state.timer);S('circle',{cx:500,cy:342,r:62,fill:'#0C1118',stroke:'#2F3945','stroke-width':2},state.timer);state.rotorEcho=[1,2,3].map(i=>S('line',{x1:500,y1:342,x2:500,y2:286,stroke:'#8f969e','stroke-width':5,'stroke-linecap':'round',opacity:0},state.timer));state.timerArm=S('line',{x1:500,y1:342,x2:500,y2:286,stroke:'#E2E8F0','stroke-width':7,'stroke-linecap':'round'},state.timer);S('circle',{cx:500,cy:342,r:13,fill:'url(#graphite)',stroke:'#fff','stroke-width':2},state.timer);S('path',{d:'M492 253 L500 239 L508 253 Z',fill:'#5f6368'},root);
 state.gate=S('g',{filter:'url(#softShadow)'},root);state.gateL=S('path',{d:'M402 512 H450',stroke:'#5f6368','stroke-width':15,'stroke-linecap':'round'},state.gate);state.gateR=S('path',{d:'M550 512 H598',stroke:'#5f6368','stroke-width':15,'stroke-linecap':'round'},state.gate);state.gateFrame=S('rect',{x:438,y:462,width:124,height:100,rx:42,fill:'none',stroke:'#d8dde3','stroke-width':3},state.gate);state.sensorPulse=addImpactRing(root,12);state.sensor=S('circle',{cx:500,cy:462,r:8,fill:'#9aa0a6'},root);state.halo=addHalo(root,500,512,60,Q_COLORS[state.target]);state.revealPoint={x:500,y:512};
}
function updateGate(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.02,.95):0;if(phys)phys.step(simT);const base=phys?.angle||0,triggerAngle=(phys?.rotor||0)*180/Math.PI,close=clamp(phys?.jaw||0),focus=smooth(phase(p,.92,1));
 if(phys)for(const ev of phys.drain()){if(state.mutedEvents)continue;if(ev.kind==='tick')sfx('tick',ev.power||.45);else if(ev.kind==='gate')sfx('gate',1);else if(ev.kind==='capture')sfx('capture',.9)}
 const rotorInk=(1-smooth(phase(p,.72,.91)))*smooth(phase(p,.04,.13));state.rotorEcho.forEach((el,i)=>SA(el,{transform:`rotate(${triggerAngle-(i+1)*(5+i*2)} 500 342)`,opacity:reduceMotion?0:rotorInk*(.18-i*.04)}));state.timerArm.setAttribute('transform',`rotate(${triggerAngle} 500 342)`);state.cands.forEach((el,i)=>{const a=base+i*Math.PI*2/3,x=500+Math.cos(a)*285,y=342+Math.sin(a)*170,front=.9+.1*((Math.sin(a)+1)/2),sc=front*(i===target?lerp(1,1.07,focus):1);SA(el,{opacity:i===target?1:lerp(1,.38,focus)});T(el,x,y,0,sc)});const gapEdge=lerp(450,458,close);SA(state.gateL,{d:`M402 512 H${gapEdge}`,stroke:focus>.15?Q_COLORS[target]:'#5f6368'});SA(state.gateR,{d:`M${1000-gapEdge} 512 H598`,stroke:focus>.15?Q_COLORS[target]:'#5f6368'});SA(state.gateFrame,{stroke:focus>.15?Q_COLORS[target]:'#d8dde3','stroke-width':lerp(3,5,focus)});SA(state.sensor,{fill:close>.1?Q_COLORS[target]:'#9aa0a6'});impactRing(state.sensorPulse,500,462,close,Q_COLORS[target],close>0&&close<.98?1:0);SA(state.halo,{opacity:focus})
}

/* Roulette Bowl — one independent ball loses energy continuously and spirals into one of three fixed pockets. */
function buildBowl(svg,state){
 const root=S('g',{},svg),bowl=S('g',{filter:'url(#shadow)'},root);S('circle',{cx:500,cy:350,r:255,fill:STAGE_SURFACE,stroke:'#394553','stroke-width':4},bowl);S('circle',{cx:500,cy:350,r:220,fill:'#0C1219',stroke:'#2C3642','stroke-width':2},bowl);S('circle',{cx:500,cy:350,r:152,fill:'#151C25',stroke:'#35414E','stroke-width':18},bowl);
 const pocketAngles=[-90,30,150].map(d=>d*Math.PI/180);state.pocketPos=pocketAngles.map(a=>[500+Math.cos(a)*137,350+Math.sin(a)*137]);state.pockets=[];state.pocketPos.forEach((pos,i)=>{const g=S('g',{},root);S('circle',{cx:pos[0],cy:pos[1],r:49,fill:Q_TINTS[i],stroke:Q_COLORS[i],'stroke-width':3},g);S('circle',{cx:pos[0],cy:pos[1],r:32,fill:STAGE_BG,opacity:.84},g);txt(g,`Q${i+1}`,pos[0],pos[1]+1,22,{fill:Q_COLORS[i],weight:760});state.pockets.push(g)});state.trail=addTrail(root,16,3);state.ball=S('g',{filter:'url(#softShadow)'},root);state.ballCore=S('circle',{cx:0,cy:0,r:19,fill:'url(#pearl)',stroke:'#aeb6bf','stroke-width':2.3},state.ball);S('ellipse',{cx:-6,cy:-7,rx:5.5,ry:3.7,fill:'#fff',opacity:.9},state.ball);state.halo=addHalo(root,500,213,54,Q_COLORS[state.target]);state.revealPoint={x:500,y:213};if(state.gl?.ok){SA(state.ball,{opacity:0});SA(state.trail.g,{opacity:0})}
}
function updateBowl(p,t,q,state){
 const target=qIndex(q),phys=state.physics,simT=phys?phys.duration*phase(p,.02,.955):0;if(phys)phys.step(simT);const focus=smooth(phase(p,.92,1)),x=phys?.x??500,y=phys?.y??124,theta=phys?.theta||0,rad=phys?.r||226,vr=phys?.vr||0,omega=phys?.omega||0,vx=vr*Math.cos(theta)-rad*omega*Math.sin(theta),vy=vr*Math.sin(theta)+rad*omega*Math.cos(theta);
 if(phys)for(const ev of phys.drain()){if(state.mutedEvents)continue;if(ev.kind==='roll')sfx('roll',ev.power||.45);else if(ev.kind==='capture'){sfx('capture',1);state.gl?.impact(ev.x,ev.y,Q_COLORS[target],1.05,ev.nx,ev.ny)}}
 const depth=clamp((y-110)/500),depthScale=lerp(.90,1.08,depth),sc=depthScale*lerp(1,1.04,easeOutBack(focus));T(state.ball,x,y,theta*180/Math.PI+90,sc,sc);SA(state.ballCore,{stroke:focus>.12?Q_COLORS[target]:'#aeb6bf','stroke-width':lerp(2.3,5,focus)});state.pockets.forEach((el,i)=>SA(el,{opacity:i===target?1:lerp(1,.38,focus)}));const [hx,hy]=state.pocketPos[target];state.halo.setAttribute('transform',`translate(${hx-500} ${hy-213})`);SA(state.halo,{opacity:focus});state.revealPoint={x:hx,y:hy};if(!state.gl?.ok)updateTrail(state.trail,state,'bowl',x,y,t,1-focus,focus>.25?Q_COLORS[target]:'#c4cad1');if(state.gl?.ok)state.gl.ball(x,y,19*sc,{base:'#e0e5ea',edge:'#89919a',focus:Q_COLORS[target],focusAmount:focus,vx,vy})
}

const builders={wheel:buildWheel,plinko:buildPlinko,arena:buildArena,rail:buildRail,gate:buildGate,bowl:buildBowl},updaters={wheel:updateWheel,plinko:updatePlinko,arena:updateArena,rail:updateRail,gate:updateGate,bowl:updateBowl};
const engine={svg:null,gl:null,scene:null,q:null,state:{},raf:0,started:0,duration:1,running:false,resolve:null,runId:0,
 mount(scene,q){this.stop();this.scene=scene;this.q=q;const seed=Math.random()*1000,target=qIndex(q),savedCanvas=this.gl?.canvas||null;sceneEl.dataset.scene=scene.id;sceneEl.innerHTML='';this.svg=S('svg',{class:'scene-svg',viewBox:'0 0 1000 700','preserveAspectRatio':'xMidYMid meet','aria-label':'抽籤動畫'},sceneEl);if(V12){if(!this.gl)this.gl=new V12.GLRenderer(sceneEl,reduceMotion);else sceneEl.appendChild(savedCanvas);this.gl.reset()}this.state={seed,target,revealPoint:{x:500,y:350},mutedEvents:true,gl:this.gl,physics:V12?.createPhysics(scene.id,target,seed)||null};addDefs(this.svg);addBackdrop(this.svg);builders[scene.id](this.svg,this.state);this.gl?.begin(performance.now());updaters[scene.id](0,0,q,this.state);this.gl?.flush();this.state.mutedEvents=false},
 play(duration){this.duration=duration;this.started=performance.now();this.running=true;const id=++this.runId;return new Promise(res=>{this.resolve=res;this.loop(this.started,id)})},
 loop(now,id){if(!this.running||id!==this.runId)return;const elapsed=now-this.started,p=clamp(elapsed/this.duration),t=elapsed/1000;this.gl?.begin(now);updaters[this.scene.id](p,t,this.q,this.state);this.gl?.flush();cameraSettle(this.svg,p,this.state.seed,this.gl?.canvas);if(p<1)this.raf=requestAnimationFrame(n=>this.loop(n,id));else{this.running=false;const r=this.resolve;this.resolve=null;if(r)r()}},
 stop(){cancelAnimationFrame(this.raf);this.raf=0;this.running=false;this.runId++;if(this.resolve){this.resolve();this.resolve=null}}
};
function svgPointToViewport(point){const r=sceneEl.getBoundingClientRect(),scale=Math.min(r.width/1000,r.height/700),ox=(r.width-1000*scale)/2,oy=(r.height-700*scale)/2;return{x:r.left+ox+point.x*scale,y:r.top+oy+point.y*scale}}
async function animateRevealChip(q,point){const vp=svgPointToViewport(point||{x:500,y:350}),wr=winner.getBoundingClientRect(),tx=wr.left+wr.width/2,ty=wr.top+wr.height/2,label=document.getElementById('revealBridgeLabel');label.textContent=q.id;revealBridge.style.setProperty('--bridge-color',qColor(q));revealBridge.style.left=`${vp.x}px`;revealBridge.style.top=`${vp.y}px`;revealBridge.classList.add('active');if(reduceMotion||!revealBridge.animate){await sleep(10);return}const anim=revealBridge.animate([{left:`${vp.x}px`,top:`${vp.y}px`,width:'82px',height:'82px',borderRadius:'41px',boxShadow:`0 0 0 0 #080B10,0 12px 34px rgba(0,0,0,.42)`,transform:'translate(-50%,-50%) scale(.88)'},{offset:.58,left:`${tx}px`,top:`${ty}px`,width:'70px',height:'38px',borderRadius:'999px',boxShadow:`0 0 0 150vmax #080B10,0 8px 22px rgba(0,0,0,.34)`,transform:'translate(-50%,-50%) scale(1.02)'},{left:`${tx}px`,top:`${ty}px`,width:'70px',height:'38px',borderRadius:'999px',boxShadow:`0 0 0 150vmax #080B10,0 2px 8px rgba(0,0,0,.28)`,transform:'translate(-50%,-50%) scale(1)'}],{duration:520,easing:'cubic-bezier(.22,.72,.16,1)',fill:'forwards'});await sleep(305);result.classList.add('show');result.setAttribute('aria-hidden','false');await anim.finished.catch(()=>{});anim.cancel()}
async function openQuestion(q,point){result.inert=true;resultImg.src=q.src;try{if(resultImg.decode)await resultImg.decode()}catch{}const ratio=(resultImg.naturalWidth||1)/(resultImg.naturalHeight||1);questionFrame.dataset.fit=ratio>4?'ultrawide':ratio<.9?'portrait':'standard';winner.textContent=q.id;winner.style.color=qColor(q);resultPackBtn.textContent=activePack;await animateRevealChip(q,point);result.classList.add('show');result.setAttribute('aria-hidden','false');appRoot.inert=true;result.inert=false;setState(STATE.QUESTION);revealBridge.classList.remove('active');revealBridge.removeAttribute('style');resultTone()}
function closeQuestion(){result.classList.remove('show');result.setAttribute('aria-hidden','true');appRoot.inert=false;result.inert=false;setState(STATE.READY)}
async function draw(){if(!activePack){showPackPicker();return}if(busy||![STATE.READY,STATE.QUESTION].includes(appState))return;ensureAudio();result.classList.remove('show');result.setAttribute('aria-hidden','true');const scene=chooseScene(),q=questions[chooseQuestion()],base={wheel:3300,plinko:3100,arena:3400,rail:3250,gate:3350,bowl:3300},pace=drawCount===0?1:.88,duration=reduceMotion?620:Math.round(base[scene.id]*pace);drawCount++;try{engine.mount(scene,q);setState(STATE.FOCUSING);await sleep(reduceMotion?10:drawCount===1?240:180);setState(STATE.ANIMATING);await engine.play(duration);setState(STATE.REVEALING);await sleep(reduceMotion?10:180);await openQuestion(q,engine.state.revealPoint)}catch(e){console.error(e);engine.stop();setState(STATE.READY);toastMsg('請再試一次')}}

packBtn.onclick=showPackPicker;resultPackBtn.onclick=()=>{closeQuestion();showPackPicker()};packOptions.forEach(b=>b.onclick=()=>selectPack(b.dataset.pack));soundBtn.onclick=()=>{soundOn=!soundOn;try{localStorage.setItem('lucky.sound',soundOn?'on':'off')}catch{}if(soundOn)ensureAudio();updateSound()};drawBtn.onclick=draw;nextBtn.onclick=async()=>{closeQuestion();await sleep(50);draw()};
document.addEventListener('keydown',e=>{if(packPicker.classList.contains('show'))return;if(e.key===' '||e.key==='Enter'){e.preventDefault();result.classList.contains('show')?nextBtn.click():draw()}if(e.key==='Escape'&&result.classList.contains('show'))closeQuestion()});
updateSound();setState(STATE.PACK);const urlPack=packFromUrl();if(urlPack)selectPack(urlPack);else showPackPicker();
})();
